// === INTERSHIP ===


export const GET_INTERSHIP_LIST = 'GET_INTERSHIP_LIST';

export const GET_COURSE_LIST = 'GET_COURSE_LIST';

export const CREATE_NEW_INTERN = 'CREATE_NEW_INTERN';

export const UPDATE_INTERN = 'UPDATE_INTERN';

export const DELETE_INTERN = 'DELETE_INTERN';

export const LOGIN_INTERSHIP_LIST = "LOGIN_INTERSHIP_LIST";

export const ADD_DATA_TO_API = 'ADD_DATA_TO_API'

export const UPLOAD_FILES = 'UPLOAD_FILES';

// === SCHEDULE TOIEC ===


export const GET_TOEIC_SCHEDULE_LIST = 'GET_TOEIC_SCHEDULE_LIST';

export const ADD_TOEIC_SCHEDULE = "ADD_TOEIC_SCHEDULE";

export const DELETE_TOEIC_SCHEDULE = "DELETE_TOEIC_SCHEDULE";

export const EDIT_TOEIC_SCHEDULE ="EDIT_TOEIC_SCHEDULE";